# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GradeRecord(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subject: str=None, grade: int=None):  # noqa: E501
        """GradeRecord - a model defined in Swagger

        :param subject: The subject of this GradeRecord.  # noqa: E501
        :type subject: str
        :param grade: The grade of this GradeRecord.  # noqa: E501
        :type grade: int
        """
        self.swagger_types = {
            'subject': str,
            'grade': float
        }

        self.attribute_map = {
            'subjec': 'subject',
            'grade': 'grade'
        }
        self._subject = subject
        self._grade = grade

    @classmethod
    def from_dict(cls, dikt) -> 'GradeRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GradeRecord of this GradeRecord.  # noqa: E501
        :rtype: GradeRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subject(self) -> str:
        """Gets the subject of this GradeRecord.


        :return: The subject of this GradeRecord.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject: str):
        """Sets the subject of this GradeRecord.


        :param subject: The subject of this GradeRecord.
        :type subject: str
        """
        if subject is None:
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def grade(self) -> int:
        """Gets the grade of this GradeRecord.


        :return: The grade of this GradeRecord.
        :rtype: int
        """
        return self._grade

    @grade.setter
    def grade(self, grade: int):
        """Sets the grade of this GradeRecord.


        :param grade: The grade of this GradeRecord.
        :type grade: int
        """
        if grade is None:
            raise ValueError("Invalid value for `grade`, must not be `None`")  # noqa: E501

        self._grade = grade
